#!/bin/bash

#############################
####### BUILDTEST_ONE #######
#############################
#
# Author: Jacob Hassold <jhassold@dcscorp.com>
#
# Builds and tests the specified ROS 2 package
# Assumes that the ROS 2 package lives somewhere inside ~/ros2_ws

function log_command(){
	echo "Executing: " $@
	$@
}

PACKAGE=$1
cd ~/ros2_ws
log_command colcon build --symlink-install --packages-select $PACKAGE --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
if [ $? = 0 ]; then
	printf "\n++++++++++++++++++++++++++++\n"
	printf "++++Beginning testing...++++\n"
	printf "++++++++++++++++++++++++++++\n"
	log_command colcon test --packages-select $PACKAGE
fi
cd -
